<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <h3><?php _e('Check health'); ?></h3>
    <div class="progress progress-striped active mb-3">
        <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $params['percent']; ?>"
             aria-valuemin="0"
             aria-valuemax="100" style="width: <?php echo $params['percent']; ?>%">
            <?php echo intval($params['percent']); ?> % Complete
        </div>
    </div>
    <?php if (!empty($nextUrl)) { ?>
        <div class="alert alert-warning" role="alert">
            <?php _e('work on update url health, please wait !'); ?>
        </div>
        <script>
            window.setTimeout(function () {
                window.location.href = '<?php echo $nextUrl; ?>'
            }, 1000)
        </script>
    <?php } ?>
</div>