<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><?php _e('Generate XML file'); ?></h3>
        </div>
        <div class="card-body">
            <p>
                <?php _e(
                    'Sitemap XML file generated on two steps, first new file generated on upload/sitemap and after that you need cope this file to website root. you can copy XML file by (( Copy to root )) button on this page, But if your server setting does not support this action you need copy XML file to website root manually by FTP client'
                ); ?>
            </p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-success">
                <strong><i class="fas fa-check-square"></i> <?php _e('Step 1'); ?></strong>
                <?php _e('New XML file generated'); ?> <span class="badge badge-success"><?php _e('Completed'); ?></span>
            </li>
            <li class="list-group-item list-group-item-success">
                <strong><i class="fas fa-check-square"></i> <?php _e('Step 2'); ?></strong>
                <?php _e('Copy XML file to website root'); ?> <span class="badge badge-success"><?php _e('Completed'); ?></span>
            </li>
        </ul>
        <div class="card-body">
            <a title="<?php _e('‌Back to index'); ?>" href="<?php echo $this->escape($url); ?>" class="card-link">
                <?php _e('‌Back to index'); ?>
            </a>
        </div>
    </div>
</div>