<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="sitemap"> 
	<h3><?php _e('List of module links'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('URL'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($links as $link) { ?>
        <tr>
			<td><?php echo $this->escape($link['id']); ?></td>
            <td>
            	<p><?php _e('Loc'); ?> : <?php echo $this->escape($link['loc']); ?></p>
            	<p>
            		<span class="label label-primary"><?php _e('Time'); ?> : <?php echo $this->escape($link['time_create']); ?></span>
            		<span class="label label-primary"><?php _e('Module'); ?> : <?php echo $this->escape($link['module']); ?></span>
            		<span class="label label-primary"><?php _e('Table'); ?> : <?php echo $this->escape($link['table']); ?></span>
            		<span class="label label-primary"><?php _e('Item'); ?> : <?php echo $this->escape($link['item']); ?></span>
            	</p>
            </td>
            <td>
				<a class="btn btn-primary" title="<?php _e('Add as top'); ?>" href="<?php echo $this->url('', array('action' => 'topadd', 'id' => $link['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Add as top'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'listdelete', 'id' => $link['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
            </td>
		</tr>	
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>