<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="sitemap"> 
	<div class="btn-group">
	   <a class="btn" title="<?php _e('Add Link'); ?>" href="<?php echo $this->url('', array('action' => 'topupdate')); ?>"><i class="icon-file"></i> <?php _e('Add Link'); ?></a>
	</div>
	<h3><?php _e('List of top links'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('URL'); ?></th>
			<th><?php _e('Change frequency'); ?></th>
			<th><?php _e('Time'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($links as $link) { ?>
        <tr>
			<td><?php echo $this->escape($link['id']); ?></td>
            <td><?php echo $this->escape($link['loc']); ?></td>
            <td><?php echo $this->escape($link['changefreq']); ?></td>
            <td><?php echo $this->escape($link['create']); ?></td>
            <td>
				<div class="btn-group">
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'topupdate', 'id' => $link['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'topdelete', 'id' => $link['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
            </td>
		</tr>	
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($links, 'Sliding', 'paginator'); ?></div>
</div>