<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="sitemap"> 
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add Link'); ?>" href="<?php echo $this->url('', array('action' => 'topupdate')); ?>"><i class="fa fa-file"></i> <?php _e('Add Link'); ?></a>
	</p>
	<?php if (!empty($links)) { ?>
	<h3><?php _e('List of top links'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('URL'); ?></th>
			<th><?php _e('Change frequency'); ?></th>
			<th><?php _e('Time'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($links as $link) { ?>
        <tr>
			<td><?php echo $this->escape($link['id']); ?></td>
            <td><?php echo $this->escape($link['loc']); ?></td>
            <td><?php echo $this->escape($link['changefreq']); ?></td>
            <td><?php echo $this->escape($link['time_create']); ?></td>
            <td>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'topupdate', 'id' => $link['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'topdelete', 'id' => $link['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
            </td>
		</tr>	
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<?php } else { ?>
	<div class="alert alert-danger">
		<h4><?php _e('Empty list'); ?></h4>
		<p><?php _e('Link top table is empty, you can add your important website links on this table manually.'); ?></p>
	</div>
	<?php } ?>
</div>