<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($links)) { ?>
        <h3><?php _e('List of module links'); ?></h3>
        <p>
            <a class="btn btn-danger" href="<?php echo $this->url('', ['action' => 'deleteAllLink']); ?>"><i class="far fa-trash-alt"></i> <?php _e(
                    'Delete ALL'
                ); ?></a>
        </p>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('URL'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($links as $link) { ?>
                <?php
                if ($link['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($link['status'] == 2) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 3) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 4) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                }
                ?>
                <tr>
                    <td><span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($link['id']); ?></span></td>
                    <td>
                        <div class="clearfix"><?php _e('Loc'); ?> : <?php echo $this->escape($link['loc']); ?></div>
                        <div class="clearfix">
                            <span class="badge badge-primary"><?php _e('Time'); ?> : <?php echo $this->escape($link['time_create']); ?></span>
                            <?php if (!empty($link['module'])) { ?>
                                <span class="badge badge-primary"><?php _e('Module'); ?> : <?php echo $this->escape($link['module']); ?></span>
                            <?php } ?>
                            <?php if (!empty($link['table'])) { ?>
                                <span class="badge badge-primary"><?php _e('Table'); ?> : <?php echo $this->escape($link['table']); ?></span>
                            <?php } ?>
                            <?php if (!empty($link['item'])) { ?>
                                <span class="badge badge-primary"><?php _e('Item'); ?> : <?php echo $this->escape($link['item']); ?></span>
                            <?php } ?>
                        </div>
                    </td>
                    <td>
                        <?php if ($link['top'] == 0) { ?>
                            <a class="btn btn-success" title="<?php _e('Add as top'); ?>"
                               href="<?php echo $this->url('', ['action' => 'topAdd', 'id' => $link['id']]); ?>"><i class="fas fa-edit"></i> <?php _e(
                                    'Add as top'
                                ); ?></a>
                        <?php } ?>
                        <a class="btn btn-danger" title="<?php _e('Delete'); ?>"
                           href="<?php echo $this->url('', ['action' => 'deleteLink', 'id' => $link['id']]); ?>"><i class="far fa-trash-alt"></i> <?php _e(
                                'Delete'
                            ); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-warning"><?php _e('Draft'); ?></span>
            <span class="badge badge-warning"><?php _e('Private'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger">
            <h4><?php _e('Empty list'); ?></h4>
            <p><?php _e(
                    'Link list table is empty, when you submit new entry on modules that support sitemap, sitemap information add automatically on this part'
                ); ?></p>
        </div>
    <?php } ?>
</div>