<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($links)) { ?>
        <h3><?php _e('List of top links'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('URL'); ?></th>
                <th><?php _e('Change frequency'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($links as $link) { ?>
                <?php if ($link['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($link['status'] == 2) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 3) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 4) {
                    $badgeIdClass = 'badge-warning';
                } elseif ($link['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } ?>
                <tr>
                    <td><span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($link['id']); ?></span></td>
                    <td><?php echo $this->escape($link['loc']); ?></td>
                    <td><?php echo $this->escape($link['changefreq']); ?></td>
                    <td><?php echo $this->escape($link['time_create']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $link['id']]); ?>"><i class="fas fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                        <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                           href="<?php echo $this->url('', ['action' => 'deleteLink', 'id' => $link['id']]); ?>"><i class="far fa-trash-alt"></i> <?php _e(
                                'Delete'
                            ); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="mb-3 p-3 bg-light">
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-warning"><?php _e('Draft'); ?></span>
            <span class="badge badge-warning"><?php _e('Private'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger">
            <h4><?php _e('Empty list'); ?></h4>
            <p><?php _e('Link top table is empty, you can add your important website links on this table manually.'); ?></p>
        </div>
    <?php } ?>
</div>